--CREACION DE USUARIOS

CREATE USER USER5 IDENTIFIED BY 123;

CREATE USER RODOLFO IDENTIFIED BY mnp;

--LISTAR TODOS LOS USUARIOS

SELECT * FROM DBA_USERS;

SELECT * FROM DBA_USERS WHERE USERNAME = 'USER5';


--ASIGNACION DE ROL DBA A UN USUARIO

GRANT DBA TO USER5;

--EL USUARIO AHORA ESTA HABILITADO PARA CONECTARSE

--ELIMINACION DE UN USUARIO

DROP USER RODOLFO;

--CAMBIO DE CREDENCIALES (CONSTRASEÑA)

ALTER USER USER5 IDENTIFIED BY 321;


--BLOQUEO Y DESBLOQUEO DE CUENTAS, POR EL ADMINISTRADOR

--BLOQUEO
ALTER USER USER5 ACCOUNT LOCK;

--DESBLOQUEO
ALTER USER USER5 ACCOUNT UNLOCK;


--EXPIRACION DE PASSWORD, IMPOSIBLE CONTECTARSE
ALTER USER USER5 PASSWORD EXPIRE;

--LISTAR USUARIOS CONECTADOS
SELECT * FROM V$SESSION ORDER BY USERNAME;

