--CREACION DE UN TABLESPACE ADECUADO PARA EL ESPACIO DE TRABAJO

CREATE TABLESPACE TBS_COMERCIAL
DATAFILE 'D:\Oracle 11g\MisTableSpaces\DF_COMPROBANTES_COMERCIAL.DBF' SIZE 100M;

--CREACION DE UN USUARIO 

CREATE USER COMERCIAL IDENTIFIED BY 123
DEFAULT TABLESPACE TBS_COMERCIAL;

--PRIVILEGIOS ASIGNADOS
GRANT DBA TO COMERCIAL;
--PRIVILEGIOS ASIGNADOS
GRANT DBA TO COMERCIAL;

--REALIZAR UNA CONEXION Y CONTINUAR
    --CREACION DE UNA TABLA REGULAR EN EL TBS ACTUAL
    
    CREATE TABLE COMPROBANTE
    (
        ID NUMBER(10),
        ORIGEN VARCHAR2(20),
        FECHA DATE,
        TIPO_PAGO CHAR(10),
        ESTADO CHAR(1)
    );
    
    SELECT * FROM COMPROBANTE;
    
    --TABLESPACE  DONDE SE ALMACENO LA TABLA 'COMPROBANTES'
    SELECT * FROM DBA_TABLES 
    WHERE TABLE_NAME = 'COMPROBANTE';
    
    --SEGUN EL RESULTADO DE LA CONSULTA, ESTA GUARDADO EN TBS_COMERCIAL
    
    --INSERCION DE 1200K REGISTROS
    --500 000
    INSERT INTO COMPROBANTE
    SELECT LEVEL, 'ASIA', SYSDATE, 'CONTADO', 1
    FROM DUAL CONNECT BY LEVEL <= 500000;
    
    --700 000
    INSERT INTO COMPROBANTE
    SELECT LEVEL, 'EUROPA', SYSDATE, 'CONTADO', 1
    FROM DUAL CONNECT BY LEVEL <= 700000;
    
    COMMIT;
    
    SELECT * FROM COMPROBANTE;
    
    --VERIFICAR EL NUMERO DE REGISTROS CON COUNT(*)
    SELECT COUNT(*) FROM COMPROBANTE;


    
--CREACION DE SECUENCIAS
CREATE SEQUENCE SQ_PRUEBA START WITH 10;

--EDITAR Y MOVER EL SIGUIENTE VALOR
SELECT SQ_PRUEBA.NEXTVAL FROM DUAL;

--VALOR ACTUAL
SELECT SQ_PRUEBA.CURRVAL FROM DUAL;


--CREACION DE UNA TABLA CON USO DE SECUENCIAS
CREATE SEQUENCE SQ_ARTICULO START WITH 1;

--ORACLE 12C PERMITE ASIGNAR LA SECUENCIA EN LA CREACION DE LA TABLA
CREATE TABLE ARTICULO
(
    ID INTEGER DEFAULT SQ_ARTICULO.NEXTVAL,
    NOMBRE VARCHAR(100),
    ESTADO INTEGER
);

--POR ENDE NO ES NECESARIO INDICAR EL ID AL MOMENTO DE INSERTAR
INSERT INTO ARTICULO(NOMBRE,ESTADO)
VALUES ('MESA',1)

INSERT INTO ARTICULO(NOMBRE,ESTADO)
VALUES ('PUERTA',2);

--ORACLE 11C
    CREATE TABLE ARTICULO
    (
        ID INTEGER,
        NOMBRE VARCHAR(100),
        ESTADO INTEGER
    );
    
    
    INSERT INTO ARTICULO(ID,NOMBRE,ESTADO) VALUES
    (SQ_ARTICULO.NEXTVAL, 'RAFAEL',2);

COMMIT;

--REVISION DE LA TABLA
SELECT * FROM ARTICULO;
DESC ARTICULO;

--CONSULTA DEL NUMERO DE LA SECC ACTUAL
SELECT SQ_ARTICULO.CURRVAL FROM DUAL;


--CREACION DE TABLAS CON COLUMNA IDENTITY DE USO OBLIGATORIO
CREATE TABLE CLIENTE(
    ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    RAZSOC VARCHAR2(30)
);

































